package:
  name: 'nionswift-video-capture'
  version: '0.2.2'

source:
  git_rev: 0.2.2
  git_url: https://github.com/nion-software/nionswift-video-capture.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.8
    - nionswift >=0.16.0,<0.17.0
    - nionswift-instrumentation >=0.20.0,<0.21.0
    - opencv

test:
  imports:
    - nionswift_plugin.nionswift_video_capture

about:
  home: https://github.com/nion-software/nionswift-video-capture
  license: GPL-3.0
  summary: "A video capture package for Nion Swift."
  description: "A video capture package for Nion Swift."

extra:
  recipe-maintainers:
    cmeyer
