package:
  name: 'nionswift-video-capture'
  version: '2.7.1'

source:
  git_rev: 2.7.1
  git_url: https://github.com/nion-software/nionswift-video-capture.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.12
    - nionswift >=16.15,<17.0
    - nionswift-instrumentation >=23.4,<24.0

test:
  imports:
    - nionswift_plugin.nionswift_video_capture

about:
  home: https://github.com/nion-software/nionswift-video-capture
  license: GPL-3.0
  summary: "A video capture package for Nion Swift."
  description: "A video capture package for Nion Swift."

extra:
  recipe-maintainers:
    cmeyer
