package:
  name: 'nionswift-video-capture'
  version: '2.6.1'
  # NOTE: reset build number

source:
  git_rev: 2.6.1
  git_url: https://github.com/nion-software/nionswift-video-capture.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.11
    - nionswift >=16.9.0,<17.0.0
    - nionswift-instrumentation >=22.0.0,<24.0.0

test:
  imports:
    - nionswift_plugin.nionswift_video_capture

about:
  home: https://github.com/nion-software/nionswift-video-capture
  license: GPL-3.0
  summary: "A video capture package for Nion Swift."
  description: "A video capture package for Nion Swift."

extra:
  recipe-maintainers:
    cmeyer
